#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MetaCellFormer.PY

Standalone Python script converted from the provided Jupyter workflow.
The input is the pretrain .h5ad generated by train-saturn.py.

Main features:
1. Load SATURN pretrain output (.h5ad)
2. Train a Transformer-based embedding model with:
   - SoftTriple loss
   - within-class variance loss
   - cross-species MMD loss
3. Generate embeddings / UMAP / Leiden clustering
4. Save result .h5ad and figures
5. Optional cluster-merging refinement
6. Optional unsupervised refinement

Example:
python MetaCellFormer.PY \
  --input_h5ad ./out/saturn_results/test256_data_xxx_pretrain.h5ad \
  --output_prefix MetaCellFormer_run \
  --device cuda:0
"""

import os
import random
import argparse
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import scanpy as sc
import umap
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import pairwise_distances


# ================================
# Utilities
# ================================

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


# ================================
# Dataset
# ================================

class SingleCellDataset(Dataset):
    def __init__(self, features, labels, species_labels):
        self.features = features
        self.labels = labels
        self.species_labels = species_labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return (
            torch.tensor(self.features[idx], dtype=torch.float32),
            torch.tensor(self.labels[idx], dtype=torch.long),
            torch.tensor(self.species_labels[idx], dtype=torch.long),
        )


class EmbeddingDataset(Dataset):
    def __init__(self, features, labels):
        self.X = torch.tensor(features, dtype=torch.float32)
        self.y = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# ================================
# Losses
# ================================

class SoftTripleLoss(nn.Module):
    """Simplified SoftTriple loss."""

    def __init__(self, embedding_dim, n_classes, n_centers=5, la=10.0, gamma=0.1, tau=0.2):
        super().__init__()
        self.la = la
        self.gamma = gamma
        self.tau = tau
        self.n_classes = n_classes
        self.n_centers = n_centers

        self.centers = nn.Parameter(
            torch.randn(n_classes * n_centers, embedding_dim) / np.sqrt(embedding_dim)
        )
        self.weight = nn.Parameter(torch.ones(n_classes, n_centers) / n_centers)

    def forward(self, x, labels):
        x = F.normalize(x, dim=1)
        centers = F.normalize(self.centers, dim=1)

        sim = torch.matmul(x, centers.t())
        batch_size = x.size(0)
        sim = sim.view(batch_size, self.n_classes, self.n_centers)

        weight = F.softmax(self.weight, dim=1)
        sim_weighted = torch.sum(sim * weight.unsqueeze(0), dim=2)

        mask = torch.zeros_like(sim_weighted).scatter_(1, labels.unsqueeze(1), 1)
        sim_target = torch.sum(sim_weighted * mask, dim=1)
        sim_others = torch.max(sim_weighted * (1 - mask), dim=1)[0]

        loss = torch.mean(F.softplus(self.la * (sim_others - sim_target + self.gamma)))
        return loss


def variance_loss(embeddings, labels):
    """Within-class compactness loss."""
    unique_labels = labels.unique()
    loss = torch.tensor(0.0, device=embeddings.device)
    count = 0

    for lab in unique_labels:
        mask = labels == lab
        cluster = embeddings[mask]
        if cluster.size(0) < 2:
            continue
        center = cluster.mean(dim=0, keepdim=True)
        loss = loss + ((cluster - center) ** 2).sum(dim=1).mean()
        count += 1

    if count == 0:
        return torch.tensor(0.0, device=embeddings.device)
    return loss / count


def mmd_loss(source, target, sigma=1.0):
    """RBF-kernel MMD."""
    if source.size(0) == 0 or target.size(0) == 0:
        return torch.tensor(0.0, device=source.device)

    def gaussian_kernel(x, y, sigma_):
        x_norm = (x ** 2).sum(dim=1).view(-1, 1)
        y_norm = (y ** 2).sum(dim=1).view(1, -1)
        dist = x_norm + y_norm - 2.0 * torch.mm(x, y.t())
        return torch.exp(-dist / (2 * sigma_ ** 2))

    k_xx = gaussian_kernel(source, source, sigma)
    k_yy = gaussian_kernel(target, target, sigma)
    k_xy = gaussian_kernel(source, target, sigma)

    return k_xx.mean() + k_yy.mean() - 2 * k_xy.mean()


def cross_species_mmd(embeddings, labels, species_labels, sigma=1.0):
    """MMD alignment across species within each cell type."""
    device = embeddings.device
    unique_labels = labels.unique()
    total_mmd = torch.tensor(0.0, device=device)
    count = 0

    for lab in unique_labels:
        mask_lab = labels == lab
        if mask_lab.sum() < 2:
            continue

        emb_lab = embeddings[mask_lab]
        species_lab = species_labels[mask_lab]
        unique_species = species_lab.unique()
        if unique_species.numel() < 2:
            continue

        for i in range(len(unique_species)):
            for j in range(i + 1, len(unique_species)):
                si = unique_species[i]
                sj = unique_species[j]
                emb_i = emb_lab[species_lab == si]
                emb_j = emb_lab[species_lab == sj]
                if emb_i.size(0) == 0 or emb_j.size(0) == 0:
                    continue
                total_mmd = total_mmd + mmd_loss(emb_i, emb_j, sigma=sigma)
                count += 1

    if count == 0:
        return torch.tensor(0.0, device=device)
    return total_mmd / count


# ================================
# Models
# ================================

class EmbeddingModel(nn.Module):
    """Transformer encoder for cell embeddings."""

    def __init__(self, input_dim, embedding_dim=256, num_heads=4, num_layers=1, hidden_dim=256, dropout=0.2):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, hidden_dim)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * 4,
            batch_first=True,
            dropout=dropout,
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.out_proj = nn.Linear(hidden_dim, embedding_dim)

    def forward(self, x):
        # x: [B, D] -> [1, B, H]
        x = self.input_proj(x)
        x = x.unsqueeze(0)
        x = self.encoder(x)
        x = self.out_proj(x).squeeze(0)
        return x


class RefineMLP(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, dim),
            nn.ReLU(),
            nn.Linear(dim, dim),
        )

    def forward(self, x):
        return self.net(x)


class CenterLoss(nn.Module):
    def __init__(self, num_classes, feat_dim):
        super().__init__()
        self.centers = nn.Parameter(torch.randn(num_classes, feat_dim))

    def forward(self, feats, labels):
        centers_batch = self.centers[labels]
        return F.mse_loss(feats, centers_batch)


# ================================
# Data preparation
# ================================

def load_and_prepare_data(input_h5ad: str):
    adata = sc.read(input_h5ad)
    print("Loaded AnnData:", adata)

    required_cols = ["labels2", "species"]
    missing = [c for c in required_cols if c not in adata.obs.columns]
    if missing:
        raise ValueError(f"Input h5ad is missing required obs columns: {missing}")

    adata = adata[~adata.obs["labels2"].isna() & ~adata.obs["species"].isna()].copy()

    label_encoder = LabelEncoder()
    adata.obs["labels2_encoded"] = label_encoder.fit_transform(adata.obs["labels2"])
    n_classes = len(label_encoder.classes_)

    species_encoder = LabelEncoder()
    adata.obs["species_encoded"] = species_encoder.fit_transform(adata.obs["species"])
    n_species = len(species_encoder.classes_)

    # Standardize adata.X
    sc.pp.scale(adata)

    features = adata.X.A if hasattr(adata.X, "A") else adata.X
    features = np.asarray(features, dtype=np.float32)
    labels = adata.obs["labels2_encoded"].values
    species_labels = adata.obs["species_encoded"].values

    print(f"Number of classes: {n_classes}")
    print(f"Number of species: {n_species}")
    print(f"Feature matrix shape: {features.shape}")

    return adata, features, labels, species_labels, label_encoder, species_encoder


# ================================
# Training / embedding
# ================================

def train_embedding_model(
    features,
    labels,
    species_labels,
    device,
    embedding_dim=256,
    batch_size=1024,
    epochs=50,
    lr=1e-3,
    n_centers=2,
    lambda_var=0.2,
    lambda_mmd=0.2,
    num_heads=4,
    num_layers=1,
    hidden_dim=256,
    num_workers=0,
):
    dataset = SingleCellDataset(features, labels, species_labels)
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )

    model = EmbeddingModel(
        input_dim=features.shape[1],
        embedding_dim=embedding_dim,
        num_heads=num_heads,
        num_layers=num_layers,
        hidden_dim=hidden_dim,
    ).to(device)

    criterion = SoftTripleLoss(
        embedding_dim=embedding_dim,
        n_classes=len(np.unique(labels)),
        n_centers=n_centers,
    ).to(device)

    optimizer = torch.optim.Adam(list(model.parameters()) + list(criterion.parameters()), lr=lr)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", patience=5, factor=0.5
    )

    loss_history = []
    soft_history = []
    var_history = []
    mmd_history = []

    print("\nStart training...")
    for epoch in range(epochs):
        model.train()
        running_total = 0.0
        running_soft = 0.0
        running_var = 0.0
        running_mmd = 0.0
        seen = 0

        for batch_features, batch_labels, batch_species in dataloader:
            batch_features = batch_features.to(device)
            batch_labels = batch_labels.to(device)
            batch_species = batch_species.to(device)

            embeddings = model(batch_features)
            loss_softtriple = criterion(embeddings, batch_labels)
            loss_var = variance_loss(embeddings, batch_labels)
            loss_mmd = cross_species_mmd(embeddings, batch_labels, batch_species, sigma=1.0)
            loss = loss_softtriple + lambda_var * loss_var + lambda_mmd * loss_mmd

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            bs = batch_features.size(0)
            seen += bs
            running_total += loss.item() * bs
            running_soft += loss_softtriple.item() * bs
            running_var += loss_var.item() * bs
            running_mmd += loss_mmd.item() * bs

        epoch_loss = running_total / seen
        epoch_soft = running_soft / seen
        epoch_var = running_var / seen
        epoch_mmd = running_mmd / seen

        loss_history.append(epoch_loss)
        soft_history.append(epoch_soft)
        var_history.append(epoch_var)
        mmd_history.append(epoch_mmd)
        scheduler.step(epoch_loss)

        print(
            f"Epoch [{epoch + 1}/{epochs}] | "
            f"Loss: {epoch_loss:.4f} | "
            f"SoftTriple: {epoch_soft:.4f} | "
            f"Var: {epoch_var:.4f} | "
            f"MMD: {epoch_mmd:.4f}"
        )

    history = {
        "total": loss_history,
        "softtriple": soft_history,
        "variance": var_history,
        "mmd": mmd_history,
    }
    return model, criterion, history


def infer_embeddings(model, features, batch_size, device):
    model.eval()
    all_embeddings = []
    with torch.no_grad():
        for i in range(0, len(features), batch_size):
            batch_features = torch.tensor(features[i:i + batch_size], dtype=torch.float32).to(device)
            emb = model(batch_features)
            all_embeddings.append(emb.cpu().numpy())
    return np.vstack(all_embeddings)


# ================================
# Visualization / clustering
# ================================

def plot_loss_curves(history, out_path: Path):
    plt.figure(figsize=(8, 6))
    plt.plot(history["total"], label="Total Loss", linewidth=2)
    plt.plot(history["softtriple"], label="SoftTriple Loss", linewidth=1)
    plt.plot(history["variance"], label="Variance Loss", linewidth=1)
    plt.plot(history["mmd"], label="MMD Loss", linewidth=1)
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training Loss Curve")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


def run_umap_and_leiden(adata, embed_key, seed, resolution=1.0, n_neighbors=15, min_dist=0.5, leiden_key="leiden_transformer"):
    reducer = umap.UMAP(
        n_neighbors=n_neighbors,
        min_dist=min_dist,
        n_components=2,
        random_state=seed,
    )
    umap_embeddings = reducer.fit_transform(adata.obsm[embed_key])
    adata.obsm["X_umap"] = umap_embeddings

    sc.pp.neighbors(adata, use_rep=embed_key, random_state=seed)
    sc.tl.leiden(adata, resolution=resolution, key_added=leiden_key, random_state=seed)
    return adata


def save_umap_plot(adata, color, out_path: Path, title="", legend_loc="right margin", frameon=True, size=None, alpha=None, show=False):
    sc.set_figure_params(dpi=150, facecolor="white")
    plt.figure(figsize=(7, 6))
    sc.pl.umap(
        adata,
        color=color,
        title=title,
        legend_loc=legend_loc,
        frameon=frameon,
        size=size,
        alpha=alpha,
        show=False,
    )
    plt.tight_layout()
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    if show:
        plt.show()
    plt.close()


def save_large_small_label_plots(adata, threshold, out_dir: Path):
    ct_counts = adata.obs["labels2"].value_counts(dropna=False)
    large_types = ct_counts[ct_counts > threshold].index
    small_types = ct_counts[ct_counts <= threshold].index

    print(f"labels2 > {threshold}: {len(large_types)} cell types")
    print(f"labels2 <= {threshold}: {len(small_types)} cell types")

    # Large only
    adata_large = adata[adata.obs["labels2"].isin(large_types)].copy()
    adata_large.obs["labels2"] = adata_large.obs["labels2"].astype("category").cat.remove_unused_categories()
    plt.figure(figsize=(7, 6))
    ax = sc.pl.umap(
        adata_large,
        color="labels2",
        title=f"UMAP by Cell Types (count > {threshold})",
        legend_loc="on data",
        frameon=True,
        show=False,
    )
    for t in ax.texts:
        t.set_fontsize(5)
    plt.tight_layout()
    plt.savefig(out_dir / f"umap_labels2_gt_{threshold}.png", dpi=200, bbox_inches="tight")
    plt.close()

    # Small only
    adata_small = adata[adata.obs["labels2"].isin(small_types)].copy()
    adata_small.obs["labels2"] = adata_small.obs["labels2"].astype("category").cat.remove_unused_categories()
    plt.figure(figsize=(7, 6))
    sc.pl.umap(
        adata_small,
        color="labels2",
        title=f"UMAP by Cell Types (count <= {threshold})",
        legend_loc="right margin",
        frameon=True,
        size=5,
        alpha=0.5,
        show=False,
    )
    plt.tight_layout()
    plt.savefig(out_dir / f"umap_labels2_le_{threshold}.png", dpi=200, bbox_inches="tight")
    plt.close()

    # All cells shown, only large types labeled
    adata.obs["labels2_large_only"] = adata.obs["labels2"].where(adata.obs["labels2"].isin(large_types))
    adata.obs["labels2_large_only"] = adata.obs["labels2_large_only"].astype("category")
    plt.figure(figsize=(7, 6))
    ax = sc.pl.umap(
        adata,
        color="labels2_large_only",
        title=f"UMAP by Cell Types (only labels > {threshold} shown)",
        legend_loc="on data",
        frameon=True,
        show=False,
    )
    for t in ax.texts:
        t.set_fontsize(5)
    plt.tight_layout()
    plt.savefig(out_dir / f"umap_labels2_large_only_{threshold}.png", dpi=200, bbox_inches="tight")
    plt.close()


# ================================
# Cluster merge refinement
# ================================

def propose_merge_groups(adata, cluster_key="leiden_transformer", umap_key="X_umap", percentile=5):
    clusters = adata.obs[cluster_key].astype(str).values
    unique_clusters = np.unique(clusters)
    umap_coords = adata.obsm[umap_key]

    centroids = []
    for c in unique_clusters:
        idx = np.where(clusters == c)[0]
        centroids.append(umap_coords[idx].mean(axis=0))
    centroids = np.vstack(centroids)

    dist_matrix = pairwise_distances(centroids, metric="euclidean")

    pairs = []
    for i in range(len(unique_clusters)):
        for j in range(i + 1, len(unique_clusters)):
            pairs.append((unique_clusters[i], unique_clusters[j], dist_matrix[i, j]))

    pairs_sorted = sorted(pairs, key=lambda x: x[2])
    top_pairs = pairs_sorted[:10]
    print("Top 10 closest cluster pairs by UMAP centroid distance:")
    for a, b, d in top_pairs:
        print(f"  Cluster {a} <-> {b} | dist = {d:.4f}")

    threshold = np.percentile(dist_matrix, percentile)
    edges = defaultdict(set)
    for a, b, d in pairs:
        if d <= threshold:
            edges[a].add(b)
            edges[b].add(a)

    visited = set()
    merge_groups = []

    def dfs(node, group):
        visited.add(node)
        group.append(node)
        for nei in edges[node]:
            if nei not in visited:
                dfs(nei, group)

    for node in list(edges.keys()):
        if node not in visited:
            group = []
            dfs(node, group)
            if len(group) >= 2:
                merge_groups.append(group)

    print("Suggested merge_groups:", merge_groups)
    return merge_groups


def build_meta_clusters(adata, merge_groups, cluster_key="leiden_transformer"):
    adata.obs[cluster_key] = adata.obs[cluster_key].astype(str)
    cluster2meta = {}
    for i, group in enumerate(merge_groups):
        meta_label = f"meta_{i}"
        for c in group:
            cluster2meta[c] = meta_label

    meta_list = []
    for c in adata.obs[cluster_key]:
        if c in cluster2meta:
            meta_list.append(cluster2meta[c])
        else:
            meta_list.append(f"keep_{c}")

    adata.obs["meta_cluster"] = pd.Categorical(meta_list)
    return adata


def refine_with_merge_groups(adata, device, epochs=30, batch_size=2048, lr=1e-3, lambda_reg=0.1):
    z0 = adata.obsm["X_embed_transformer"].copy()
    meta_labels = adata.obs["meta_cluster"].cat.codes.values

    dataset = EmbeddingDataset(z0, meta_labels)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    dim = z0.shape[1]
    refiner = RefineMLP(dim).to(device)
    center_loss_fn = CenterLoss(len(np.unique(meta_labels)), dim).to(device)

    optimizer = torch.optim.Adam(list(refiner.parameters()) + list(center_loss_fn.parameters()), lr=lr)

    print("\nStart merge-group refinement...")
    for epoch in range(epochs):
        epoch_loss = 0.0
        for xb, yb in dataloader:
            xb = xb.to(device)
            yb = yb.to(device)

            z = refiner(xb)
            loss_c = center_loss_fn(z, yb)
            loss_r = F.mse_loss(z, xb)
            loss = loss_c + lambda_reg * loss_r

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * xb.size(0)

        epoch_loss /= len(dataset)
        print(f"Epoch {epoch + 1}/{epochs} | Loss = {epoch_loss:.4f}")

    with torch.no_grad():
        z_refined = refiner(torch.tensor(z0, dtype=torch.float32).to(device)).cpu().numpy()

    adata.obsm["X_embed_merged"] = z_refined
    sc.pp.neighbors(adata, use_rep="X_embed_merged", n_neighbors=15)
    sc.tl.leiden(adata, key_added="leiden_merged", resolution=1.0)
    sc.tl.umap(adata)
    return adata


# ================================
# Unsupervised refinement
# ================================

def build_knn_neighbors_from_embedding(adata, embed_key="X_embed_transformer", n_neighbors=15):
    adata.obsm["X_tmp_for_refine"] = adata.obsm[embed_key].copy()
    sc.pp.neighbors(adata, use_rep="X_tmp_for_refine", n_neighbors=n_neighbors, metric="euclidean")
    knn_graph = adata.obsp["connectivities"].tolil()
    neighbors = {i: knn_graph.rows[i] for i in range(adata.n_obs)}
    return neighbors


def unsupervised_refine_embeddings(adata, device, embed_key="X_embed_transformer", epochs=30, batch_size=256, lr=1e-3, lambda_reg=0.8):
    z0 = adata.obsm[embed_key].copy()
    neighbors = build_knn_neighbors_from_embedding(adata, embed_key=embed_key, n_neighbors=15)

    refiner = RefineMLP(z0.shape[1]).to(device)
    z0_torch = torch.tensor(z0, dtype=torch.float32).to(device)
    optimizer = torch.optim.Adam(refiner.parameters(), lr=lr)

    indices = np.arange(z0.shape[0])
    print("\nStart unsupervised refinement...")

    for epoch in range(epochs):
        np.random.shuffle(indices)
        epoch_loss = 0.0

        for start in range(0, len(indices), batch_size):
            batch_idx = indices[start:start + batch_size]
            batch = torch.tensor(batch_idx, device=device)

            z0_batch = z0_torch[batch]
            z_batch = refiner(z0_batch)

            pos_pairs_i = []
            pos_pairs_j = []
            batch_set = set(batch_idx.tolist()) if hasattr(batch_idx, "tolist") else set(batch_idx)

            for i in batch_idx:
                for j in neighbors[i]:
                    if j in batch_set:
                        pos_pairs_i.append(i)
                        pos_pairs_j.append(j)

            if len(pos_pairs_i) > 0:
                mapping = {cell: k for k, cell in enumerate(batch_idx)}
                pos_i = torch.tensor([mapping[i] for i in pos_pairs_i], device=device)
                pos_j = torch.tensor([mapping[j] for j in pos_pairs_j], device=device)
                loss_pull = F.mse_loss(z_batch[pos_i], z_batch[pos_j])
            else:
                loss_pull = torch.tensor(0.0, device=device)

            loss_reg = F.mse_loss(z_batch, z0_batch)
            loss = loss_pull + lambda_reg * loss_reg

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * len(batch_idx)

        epoch_loss /= len(indices)
        print(f"Epoch {epoch + 1}/{epochs} | Loss: {epoch_loss:.4f}")

    with torch.no_grad():
        z_refined = refiner(z0_torch).cpu().numpy()

    adata.obsm["X_embed_unsup_refined"] = z_refined
    sc.pp.neighbors(adata, use_rep="X_embed_unsup_refined", n_neighbors=15)
    sc.tl.leiden(adata, key_added="leiden_unsup_refined", resolution=1.0)
    sc.tl.umap(adata)
    return adata


# ================================
# Main
# ================================

def parse_args():
    parser = argparse.ArgumentParser(description="MetaCellFormer pipeline from SATURN pretrain output")
    parser.add_argument("--input_h5ad", type=str, required=True, help="Input .h5ad from train-saturn.py pretrain output")
    parser.add_argument("--output_dir", type=str, default="./MetaCellFormer_output", help="Directory to save outputs")
    parser.add_argument("--output_prefix", type=str, default="MetaCellFormer", help="Output file prefix")
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=2025)

    parser.add_argument("--embedding_dim", type=int, default=256)
    parser.add_argument("--hidden_dim", type=int, default=256)
    parser.add_argument("--num_heads", type=int, default=4)
    parser.add_argument("--num_layers", type=int, default=1)
    parser.add_argument("--batch_size", type=int, default=1024)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--n_centers", type=int, default=2)
    parser.add_argument("--lambda_var", type=float, default=0.2)
    parser.add_argument("--lambda_mmd", type=float, default=0.2)
    parser.add_argument("--num_workers", type=int, default=0)

    parser.add_argument("--umap_n_neighbors", type=int, default=15)
    parser.add_argument("--umap_min_dist", type=float, default=0.5)
    parser.add_argument("--leiden_resolution", type=float, default=1.0)
    parser.add_argument("--large_type_threshold", type=int, default=3000)

    parser.add_argument("--run_merge_refine", action="store_true", help="Run merge-group refinement")
    parser.add_argument("--merge_percentile", type=float, default=5.0, help="Percentile threshold for auto merge proposal")
    parser.add_argument("--merge_epochs", type=int, default=30)
    parser.add_argument("--merge_batch_size", type=int, default=2048)
    parser.add_argument("--merge_lr", type=float, default=1e-3)
    parser.add_argument("--merge_lambda_reg", type=float, default=0.1)

    parser.add_argument("--run_unsup_refine", action="store_true", help="Run unsupervised refinement")
    parser.add_argument("--unsup_epochs", type=int, default=30)
    parser.add_argument("--unsup_batch_size", type=int, default=256)
    parser.add_argument("--unsup_lr", type=float, default=1e-3)
    parser.add_argument("--unsup_lambda_reg", type=float, default=0.8)

    return parser.parse_args()


def main():
    args = parse_args()
    set_seed(args.seed)

    device = torch.device(args.device)
    print("Using device:", device)

    output_dir = Path(args.output_dir)
    figures_dir = output_dir / "figures"
    ensure_dir(output_dir)
    ensure_dir(figures_dir)

    # 1. Load data
    adata, features, labels, species_labels, _, _ = load_and_prepare_data(args.input_h5ad)

    # 2. Train model
    model, _, history = train_embedding_model(
        features=features,
        labels=labels,
        species_labels=species_labels,
        device=device,
        embedding_dim=args.embedding_dim,
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr=args.lr,
        n_centers=args.n_centers,
        lambda_var=args.lambda_var,
        lambda_mmd=args.lambda_mmd,
        num_heads=args.num_heads,
        num_layers=args.num_layers,
        hidden_dim=args.hidden_dim,
        num_workers=args.num_workers,
    )

    # 3. Save training curve
    plot_loss_curves(history, figures_dir / f"{args.output_prefix}_loss_curve.png")

    # 4. Infer embeddings
    print("\nGenerating embeddings for all cells...")
    all_embeddings = infer_embeddings(model, features, args.batch_size, device)
    print("Embedding shape:", all_embeddings.shape)
    adata.obsm["X_embed_transformer"] = all_embeddings

    # 5. UMAP + Leiden
    print("Running UMAP and Leiden clustering...")
    adata = run_umap_and_leiden(
        adata,
        embed_key="X_embed_transformer",
        seed=args.seed,
        resolution=args.leiden_resolution,
        n_neighbors=args.umap_n_neighbors,
        min_dist=args.umap_min_dist,
        leiden_key="leiden_transformer",
    )

    # 6. Save basic plots
    save_umap_plot(
        adata,
        color="species",
        out_path=figures_dir / f"{args.output_prefix}_umap_species.png",
        title="UMAP by Species (Transformer + SoftTriple + MMD)",
    )
    save_umap_plot(
        adata,
        color="labels2",
        out_path=figures_dir / f"{args.output_prefix}_umap_labels2.png",
        title="UMAP by Cell Types (Transformer + SoftTriple + MMD)",
    )
    save_umap_plot(
        adata,
        color="leiden_transformer",
        out_path=figures_dir / f"{args.output_prefix}_umap_leiden_transformer.png",
        title="UMAP by Leiden (Transformer + SoftTriple + MMD)",
    )
    save_large_small_label_plots(adata, args.large_type_threshold, figures_dir)

    # 7. Optional merge-group refinement
    if args.run_merge_refine:
        merge_groups = propose_merge_groups(
            adata,
            cluster_key="leiden_transformer",
            umap_key="X_umap",
            percentile=args.merge_percentile,
        )
        if len(merge_groups) > 0:
            adata = build_meta_clusters(adata, merge_groups, cluster_key="leiden_transformer")
            adata = refine_with_merge_groups(
                adata,
                device=device,
                epochs=args.merge_epochs,
                batch_size=args.merge_batch_size,
                lr=args.merge_lr,
                lambda_reg=args.merge_lambda_reg,
            )
            save_umap_plot(
                adata,
                color="leiden_merged",
                out_path=figures_dir / f"{args.output_prefix}_umap_leiden_merged.png",
                title="After merging refinement (leiden_merged)",
            )
        else:
            print("No merge groups detected; skipping merge refinement.")

    # 8. Optional unsupervised refinement
    if args.run_unsup_refine:
        adata = unsupervised_refine_embeddings(
            adata,
            device=device,
            embed_key="X_embed_transformer",
            epochs=args.unsup_epochs,
            batch_size=args.unsup_batch_size,
            lr=args.unsup_lr,
            lambda_reg=args.unsup_lambda_reg,
        )
        save_umap_plot(
            adata,
            color="leiden_unsup_refined",
            out_path=figures_dir / f"{args.output_prefix}_umap_leiden_unsup_refined.png",
            title="After unsupervised refinement (leiden_unsup_refined)",
        )

    # 9. Save output h5ad
    output_h5ad = output_dir / f"{args.output_prefix}.h5ad"
    adata.write(output_h5ad)
    print(f"\nFinal AnnData saved to: {output_h5ad}")

    # 10. Save model weights
    model_path = output_dir / f"{args.output_prefix}_model.pt"
    torch.save(model.state_dict(), model_path)
    print(f"Model weights saved to: {model_path}")


if __name__ == "__main__":
    main()
